### ISSUE TITLE
Add ability to call the correct sound processing function based on current state.

### ISSUE THREAD

**Issue by sfaletti** [richclarkson/Sabre#12]
As a User, I want to get the right sound processing behavior when I select a certain display mode.
As a Developer, I need a set of function hooks to connect the current State object to the right sound processing function.

## ToDo
- [x] Disable the button testing to speed development
- [x] register a callback for FFT analysis
- [x] register a callback for Level analysis
- [x] link the callbacks to State calls
- [x] tie the callbacks to a single update method to be called from the main loop
- [x] store data created by the sound analysis callbacks
- [x] refactor the register methods?
- [x] add registry to main file
- [x] Re-enable button test suite

**Comment by sfaletti** [comment]
@richclarkson I'm trying to figure out which Music Mode settings require FFT vs Level analysis. Based off this image, it seems like Ripple is the only setting that needs FFT. I have been drinking tonight so I may be off by a bit.
<img width="721" alt="screen shot 2018-01-27 at 11 22 02 pm" src="https://user-images.githubusercontent.com/2781296/35478983-34657266-03b9-11e8-9754-e299f8142fea.png">

**Comment by sfaletti** [comment]
#13

**Comment by richclarkson** [comment]
@sfaletti Under normal operation (e.g. a single saber) then yes only the ripple mode requires FFT as opposed to Level. But when the sabers are sold as a set of 7 sabers the user has the ability to set each saber to a specific channel (1 of 8 channels). The idea here is that the user would install the Sabers in a line and set the left most saber as the lowest channel (channel 0 - the channel that reacts most to bass) then the Saber immediately to the right of that to the next channel up (channel 1) then the Saber to the right of that to the next channel up (channel 2) and so on and so forth. This way the user now has a basic [spectrum analyser](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ10cO71BJiCwAUfIWARc3CNM9A5YuFHT6aJzyLj-fw1cRjd7Gk) that works for all the music modes (note that ripple is still the same and does not change with the above settings). Given the above the music modes do need a way to filter down to just the channel they are set to that is where I think they will need to use FFT unless there is a better way to do that filtering. Does that make sense?

![fullsizerender 3](https://user-images.githubusercontent.com/31944012/35485007-eac296e8-0426-11e8-910c-a70647d919f6.jpg)

**Comment by sfaletti** [comment]
That makes sense. When we get to the LED control functions, we can pull the Channel setting value to scale the FFT to the LEDs. However, we will also need to run FFT for everything then. I have it set up to store to separate variables anyway, so it will be easier to just run the analysis code on both FFT and Level, then use whatever value makes sense on the display side. 
I'll need to update the inner methods to call both functions, but you can define both in the main loop hooks. We can merge this PR now though, I think.
