### ISSUE TITLE
Clean up repo

### ISSUE THREAD

**Issue by sfaletti** [richclarkson/Sabre#16]
The repo is really messy, and is not very helpful in figuring out the intent of the project. It looks like one or more of the feature branches have supplanted `master` at some point. Anything that can be merged into `master` should be, and any that need to be dropped should be moved into the `archive` folder. Once they're clean we can reassess the current state of `master` and build a new project plan. To move a branch, just add "archive/" to the front of its name and Github (and Tower) will translate it to a folder structure. We can keep the archived branches out of the way until we're comfortable deleting them.

## ToDo
- [x] @richclarkson to create `2.0.0` version branch from current release branch
- [ ] @sfaletti to create new `master` that represents a viable development version
- [ ] @sfaletti to archive unused branches where appropriate
- [ ] purge unnecessary code and delete archived branches
- [ ] go forward into a brighter future

**Comment by richclarkson** [comment]
My most recent "stable" branch with the tactile button is this one: https://github.com/richclarkson/Sabre/tree/LED_animations, @sfaletti let me know what else needs cleaning up to merge the code. You can go ahead and delete all of my other branches.

**Comment by sfaletti** [comment]
I just created a pull request but it's just for review. I branched your `LED_animations` branch into one called `release/1.2.1`, which was the last semver I saw in your commit history. Keeping this as version 1.x makes sense. But before we declare it a release, please make sure it compiles and can run on the hardware. If so we can add a release tag and then there is a known good version if any orders come in between now and the next firmware version, and bug fixes can be applied if need be. I'll get into the `master` repo restructuring at some point this week.
