### ISSUE TITLE
Add ability to save settings to EPROM

### ISSUE THREAD

**Issue by sfaletti** [richclarkson/Sabre#6]
As a Sabre User, I need my deep system settings (brightness, channels, sensitivity) to be saved upon change, so I can get the same effects when I move or power cycle my Sabre. 

## TODO
- [x] create abstraction layer to Arduino EEPROM library
- [x] set and get sensitivity values from EEPROM
- [x] set and get channel values from EEPROM
- [x] set and get brightness values from EEPROM
- [x] add library calls from StateManager library
- [x] test library and integration

**Comment by sfaletti** [comment]
The code is mostly there. This needs to be tested on a device. See https://github.com/richclarkson/Sabre/commit/96cfc420dd990e733ab766a6a78bdf65d26ac68f for details.

**Comment by sfaletti** [comment]
EEPROM tests all pass. It needs a check value to set a new mcu, but I'll put that into another story.
